### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by mikeygio10** [Anders233/PlayerJoinSettings#2]
add a way to run a command when a player joins

like i want to give them a effect when they join but i dont know how or if you can

**Comment by Anders233** [comment]
Look at the configuration file, you can set the command that the player executes after clicking the button.

# Set the command to be executed when the player presses the first button
# 设置玩家按下第一个按钮时执行的命令
UIformbutton1cmd: "give {name} 297 3"

# Set the command to be executed when the player presses the second button
# 设置玩家按下第二个按钮时执行的命令
UIformbutton2cmd: "give {name} 297 1"

**Comment by 3zeroed** [comment]
Look at the configuration file, you can set the command that the player executes after clicking the button.

Set the command to be executed when the player presses the first button
设置玩家按下第一个按钮时执行的命令
UIformbutton1cmd: "give {name} 297 3"

Set the command to be executed when the player presses the second button
设置玩家按下第二个按钮时执行的命令
UIformbutton2cmd: "give {name} 297 1"

**Comment by mikeygio10** [comment]
17.04 20:20:01 [Server] Server thread/INFO Loading PlayerJoinSettings v1.1.1
17.04 20:20:01 [Server] Server thread/CRITICAL ErrorException: "yaml_parse(): reading error encountered during parsing: invalid trailing UTF-8 octet (line 1, column 1)" (EXCEPTION) in "src/pocketmine/utils/Config" at line 181
17.04 20:20:01 [Server] Server thread/DEBUG #0 (): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string yaml_parse(): reading error encountered during parsing: invalid trailing UTF-8 octet (line 1, column 1), string phar:///PMMP-1.10.0-Latest-Stable.phar/src/pocketmine/utils/Config.php, integer 181, array Array())
17.04 20:20:01 [Server] Server thread/DEBUG #1 src/pocketmine/utils/Config(181): yaml_parse(string ---..# Currently supported tags:..# .....................:..# {name}          - The name of the player...# {name}          - .................# {line}          - Switch to the next line...# {line}          - ....................# {online}        - The number of online players currently on the server...# {online}        - .............................# {max_online}    - The maximum number of players the server can accommodate..# {max_online}    - .............................# You can also use & replace with color symbols...# .................. & .....................# ----------==========<<<[Title and SubTitle]>>>==========----------...# Show title when players join? (true or false)..# .....................................(true ... false)..TitleSwitch: true...# The headline on the screen when joining (Title)..# ...............................................(.........)..Title: "&l&6 Welcome!"...# The text above the item bar when you join (SubTitle)..# ...............................................(.........)..SubTitle: "&b To the DarkSide Network"...# ----------==========<<<[Jion and Quit MSG]>>>==========----------...# Send a message when the player joins? (true or false)..# .....................................(true ... false)..MessageSwitch: true...# Private chat message sent to the player when joining (Message)..# ................................................Message: "&b Welcome to the DarkSide Network. {line}&e I wish you a happy time!"...# Undo the original player join prompt for the server? (true or false)..# ....................................................(true ... false)..UndoPlayerJoinMessage: true...# Whether to prompt the message when the player joins? (true or false)..# ...........................................................(true ... false)..PlayerJoinMessageSwitch: true...# Server broadcast message when the player joins (Player Join Message)...# ....................................................................PlayerJoinMessage: "&l&7(&9+&7) &r&a{name} &eHas Joined The Lobby"....# Undo the original player exit prompt for the server? (true or false)..# .............................................(true ... false)..UndoPlayerQuitMessage: true...# Whether to prompt the message when the player Quits? (true or false)..# .............................................(true ... false)..PlayerQuitMessageSwitch: true...# Server broadcast message when the player Quits (Player Quit Message)..# .............................................................PlayerQuitMessage: "&l&7(&c-&7) &r&a{name} &eHas left the Lobby."...# ----------==========<<<[UI form Setting]>>>==========----------...# Pop up the UI form when the player joins? (true or false)..# ..................................UI.........(true ... false)..PlayerJoinUIform: true...# Title text content above the UI form..# .........UI.......................UIformTitle: "&l&6 Welcome"...# Text content in the UI form..# .........UI..............................UIformContent: "&a Hello {name}. {line}&b Please make sure to read all the rules. {line}&e They are at spawn make sure to look around to find them"...# The first button of the UI form displays the text..# .........UI................................UIformbutton1: "&a Confirm"...# The second button of the UI form displays the text..# .........UI................................UIformbutton2: "&c Cancel"...# Click the button to execute the command? (true or false)..# ...........................(true ... false)..ButtonCommand: true...# Set the command to be executed when the player presses the first button..# .....................................................UIformbutton1cmd: "effect {player} speed 9999 2 true"...# Set the command to be executed when the player presses the second button..# .....................................................UIformbutton2cmd: "kick {player} Press Confirm to Continue".......)
17.04 20:20:01 [Server] Server thread/DEBUG #2 src/pocketmine/utils/Config(113): pocketmine\utils\Config->load(string /plugin_data/PlayerJoinSettings/config.yml, integer 2, array Array())
17.04 20:20:01 [Server] Server thread/DEBUG #3 plugins/PlayerJoinSettings_dev-51.phar/src/Anders/PlayerJoinSettings/Main(43): pocketmine\utils\Config->__construct(string /plugin_data/PlayerJoinSettings/config.yml, integer 2)
17.04 20:20:01 [Server] Server thread/DEBUG #4 src/pocketmine/plugin/PluginManager(193): Anders\PlayerJoinSettings\Main->onLoad()
17.04 20:20:01 [Server] Server thread/DEBUG #5 src/pocketmine/plugin/PluginManager(343): pocketmine\plugin\PluginManager->loadPlugin(string /plugins/PlayerJoinSettings_dev-51.phar, array Array())
17.04 20:20:01 [Server] Server thread/DEBUG #6 src/pocketmine/Server(2051): pocketmine\plugin\PluginManager->loadPlugins(string /plugins/)
17.04 20:20:01 [Server] Server thread/DEBUG #7 src/pocketmine/command/defaults/ReloadCommand(49): pocketmine\Server->reload()
17.04 20:20:01 [Server] Server thread/DEBUG #8 src/pocketmine/command/SimpleCommandMap(270): pocketmine\command\defaults\ReloadCommand->execute(pocketmine\Player object, string reload, array Array())
17.04 20:20:01 [Server] Server thread/DEBUG #9 src/pocketmine/Server(2010): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\Player object, string reload)
17.04 20:20:01 [Server] Server thread/DEBUG #10 src/pocketmine/Player(2221): pocketmine\Server->dispatchCommand(pocketmine\Player object, string reload)
17.04 20:20:01 [Server] Server thread/DEBUG #11 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(239): pocketmine\Player->chat(string /reload)
17.04 20:20:01 [Server] Server thread/DEBUG #12 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
17.04 20:20:01 [Server] Server thread/DEBUG #13 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
17.04 20:20:01 [Server] Server thread/DEBUG #14 src/pocketmine/network/mcpe/protocol/BatchPacket(119): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
17.04 20:20:01 [Server] Server thread/DEBUG #15 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
17.04 20:20:01 [Server] Server thread/DEBUG #16 src/pocketmine/Player(3114): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
17.04 20:20:01 [Server] Server thread/DEBUG #17 src/pocketmine/network/mcpe/RakLibInterface(170): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
17.04 20:20:01 [Server] Server thread/DEBUG #18 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 70.105.172.190 50384, raklib\protocol\EncapsulatedPacket object, integer 0)
17.04 20:20:01 [Server] Server thread/DEBUG #19 src/pocketmine/network/mcpe/RakLibInterface(110): raklib\server\ServerHandler->handlePacket()
17.04 20:20:01 [Server] Server thread/DEBUG #20 src/pocketmine/network/mcpe/RakLibInterface(100): pocketmine\network\mcpe\RakLibInterface->process()
17.04 20:20:01 [Server] Server thread/DEBUG #21 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
17.04 20:20:01 [Server] Server thread/DEBUG #22 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
17.04 20:20:01 [Server] Server thread/DEBUG #23 src/pocketmine/Server(2328): pocketmine\snooze\SleeperHandler->sleepUntil(double 1555532401.3459)
17.04 20:20:01 [Server] Server thread/DEBUG #24 src/pocketmine/Server(2186): pocketmine\Server->tickProcessor()
17.04 20:20:01 [Server] Server thread/DEBUG #25 src/pocketmine/Server(1765): pocketmine\Server->start()
17.04 20:20:01 [Server] Server thread/DEBUG #26 src/pocketmine/PocketMine(250): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
17.04 20:20:01 [Server] Server thread/DEBUG #27 (1): require(string phar:///PMMP-1.10.0-Latest-Stable.phar/src/pocketmine/PocketMine.php)

**Comment by mikeygio10** [comment]
says that i messed somethign up how do i fix?

**Comment by mikeygio10** [comment]
why when ever i cahange something it does not work

**Comment by 3zeroed** [comment]
This looks like a configuration file modification error.

**Comment by Anders233** [comment]
.yml 格式，你要确保 : 后有一个空格

**Comment by 3zeroed** [comment]
.yml format, you want to make sure: there is a space after
